services:
  - type: web
    name: poker-track-backend
    runtime: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: JAVA_VERSION
        value: 11
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  - type: web
    name: poker-track-frontend
    runtime: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/dist"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: poker-track-backend
          property: host
